database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: dropwizard

  # the password
  password: dropwizard

  # the JDBC URL
  url: jdbc:postgresql://192.168.0.2/dropwizard

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 30s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the timeout before a connection validation queries fail
  validationQueryTimeout: 3s

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 60s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: OFF

  # Logger-specific levels.
  loggers:

    miccab.nonblocking: OFF
    org.eclipse.jetty.server: OFF
    com.github.pgasync: OFF
    io.netty: OFF

  appenders:
    - type: console
      logFormat: "[%d{HH:mm:ss.SSS}] [%-6level] [%t] %logger{5} - %X{code} %msg %n"
    - type: file
      logFormat: "[%d{HH:mm:ss.SSS}] [%-6level] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: application.log
      archive: true
      archivedLogFilenamePattern: application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 2

server:
  type: default
  # acceptors (2) + selectors (4) + N (for requests)
  minThreads: 7
  maxThreads: 7
  adminConnectors: []
  requestLog:
     appenders: []

